replicaCount: 1

image:
  repository: mamutuberalles/helloapp #TODO build and push dockerimage here
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources: {}