name: Pipeline for application testing and building

on:
  push:
    branches: [ "master" ]
    paths:
      - '**.sh'
      - 'README.md'
      - 'requirements.txt'
      - 'LICENSE'
      - 'helloapp/**'
  workflow_dispatch:

jobs:
  build-and-test-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: python -m unittest helloapp.test