name: Pipeline for Helmchart
on:
  push:
    branches:
      - main
    paths:
      - 'charts/*'
  workflow_dispatch:
  workflow_run:
    workflows: ["Pipeline for docker containerization"]
    types: [completed]

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"


      - name: Calculate new version
        id: version
        run: |
          CURRENT_VERSION=$(yq eval '.version' charts/devops-task/Chart.yaml)
          MAJOR=$(echo $CURRENT_VERSION | cut -d. -f1)
          MINOR=$(echo $CURRENT_VERSION | cut -d. -f2)
          PATCH=$(echo $CURRENT_VERSION | cut -d. -f3)
          NEW_PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
      
      - name: Push new chart version
        run: |
          yq eval '.version = "${{ steps.version.outputs.version }}"' -i charts/devops-task/Chart.yaml
      
      - name: Commit updated Chart.yaml
        run: |
          git add charts/devops-task/Chart.yaml
          git commit -m "Bumped chart version to ${{ steps.version.outputs.version }} [skip ci]"
          git push

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"