name: Pipeline for docker contanierization

on:
  push:
    branches: [ "master" ]
    paths:
      - 'docker/*'
  workflow_dispatch:


jobs:
  build-and-push-docker:
    needs: build-and-test-app
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PAT }}

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/helloapp:latest